


export const entidades = {
    USUARIOS: 'USUARIOS',
    EMPRESAS: 'EMPRESAS',
    FASES:'FASES',
    TIPOS_MEDICION:'TIPOS_MEDICION',
    TRAMOS:'TRAMOS',
    // CADENAMIENTO : 'CADENAMIENTO',
    // OBRAS: 'OBRAS',
    CONCEPTOS_GASTOS: 'CONCEPTOS_GASTOS',
    // TIPOS_GASTOS: 'TIPOS_GASTOS',
    // COLABORADRES: 'COLABORADORES',
    ROLES: 'ROLES',
    // NOTIFICACIONES: 'NOTIFICACIONES',
    // CLIENTES: 'CLIENTES',
    // TIPOSCONCEPTOPAGO: 'TIPOSCONCEPTOPAGO',
    // TIPOSINSUMOS: 'TIPOSINSUMOS',
    // GRUPOSINSUMOS: 'GRUPOSINSUMOS',
    // INSUMOS: 'INSUMOS',
    // PROVEEDORES: 'PROVEEDORES',
    // DOCUMENTOS: 'DOCUMENTOS'
}
   